/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material You color tokens (from design system)
        'primary':                    '#2c1fe8',
        'primary-fixed':              '#e1dfff',
        'primary-fixed-dim':          '#c1c1ff',
        'primary-container':          '#4945ff',
        'on-primary':                 '#ffffff',
        'on-primary-fixed':           '#09006b',
        'on-primary-fixed-variant':   '#240ee3',
        'on-primary-container':       '#e2e0ff',

        'secondary':                  '#5d5c72',
        'secondary-fixed':            '#e2e0fa',
        'secondary-fixed-dim':        '#c6c4dd',
        'secondary-container':        '#dfddf7',
        'on-secondary':               '#ffffff',
        'on-secondary-fixed':         '#1a1a2c',
        'on-secondary-fixed-variant': '#45455a',
        'on-secondary-container':     '#616177',

        'tertiary':                   '#8b2c00',
        'tertiary-fixed':             '#ffdbcf',
        'tertiary-fixed-dim':         '#ffb59b',
        'tertiary-container':         '#b43b00',
        'on-tertiary':                '#ffffff',
        'on-tertiary-fixed':          '#380d00',
        'on-tertiary-fixed-variant':  '#822800',
        'on-tertiary-container':      '#ffdacf',

        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',

        'surface':                    '#fcf8ff',
        'surface-dim':                '#dbd8e7',
        'surface-bright':             '#fcf8ff',
        'surface-variant':            '#e4e1ef',
        'surface-tint':               '#423cf9',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f5f2ff',
        'surface-container':          '#efecfb',
        'surface-container-high':     '#e9e6f5',
        'surface-container-highest':  '#e4e1ef',

        'background':                 '#fcf8ff',
        'outline':                    '#767588',
        'outline-variant':            '#c6c4d9',
        'on-surface':                 '#1b1b25',
        'on-surface-variant':         '#464556',
        'on-background':              '#1b1b25',
        'inverse-surface':            '#302f3a',
        'inverse-on-surface':         '#f2effe',
        'inverse-primary':            '#c1c1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        xs:              '4px',
        sm:              '8px',
        md:              '16px',
        lg:              '24px',
        xl:              '32px',
        sidebar_width:   '240px',
        max_content_width: '1280px',
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        code:    ['"JetBrains Mono"', 'monospace'],
        'body-lg':  ['Inter', 'sans-serif'],
        'body-md':  ['Inter', 'sans-serif'],
        'h1':       ['Inter', 'sans-serif'],
        'h2':       ['Inter', 'sans-serif'],
        'h3':       ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'code':     ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg':  ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':  ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'h3':       ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'h2':       ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h1':       ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
